# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_win_base.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(466, 271)
        self.shutdown_btn_2 = QtWidgets.QPushButton(Form)
        self.shutdown_btn_2.setGeometry(QtCore.QRect(9, 239, 221, 23))
        self.shutdown_btn_2.setObjectName("shutdown_btn_2")
        self.shutdown_btn = QtWidgets.QPushButton(Form)
        self.shutdown_btn.setGeometry(QtCore.QRect(270, 239, 181, 23))
        self.shutdown_btn.setObjectName("shutdown_btn")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(9, 9, 448, 82))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.timeEdit = QtWidgets.QTimeEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.timeEdit.setFont(font)
        self.timeEdit.setFrame(True)
        self.timeEdit.setReadOnly(True)
        self.timeEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.timeEdit.setObjectName("timeEdit")
        self.horizontalLayout_6.addWidget(self.timeEdit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.dateEdit = QtWidgets.QDateEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.dateEdit.setFont(font)
        self.dateEdit.setReadOnly(True)
        self.dateEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_6.addWidget(self.dateEdit)
        spacerItem1 = QtWidgets.QSpacerItem(22, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.batt_lbl = QtWidgets.QLabel(self.widget)
        self.batt_lbl.setObjectName("batt_lbl")
        self.horizontalLayout_2.addWidget(self.batt_lbl)
        self.battery_bar = QtWidgets.QProgressBar(self.widget)
        self.battery_bar.setProperty("value", 24)
        self.battery_bar.setObjectName("battery_bar")
        self.horizontalLayout_2.addWidget(self.battery_bar)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.widget1 = QtWidgets.QWidget(Form)
        self.widget1.setGeometry(QtCore.QRect(9, 103, 222, 124))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cpu_temp_lbl = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.cpu_temp_lbl.setFont(font)
        self.cpu_temp_lbl.setObjectName("cpu_temp_lbl")
        self.horizontalLayout.addWidget(self.cpu_temp_lbl)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.cpu_temp_val = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.cpu_temp_val.setFont(font)
        self.cpu_temp_val.setObjectName("cpu_temp_val")
        self.horizontalLayout.addWidget(self.cpu_temp_val)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.bot_uptime_lbl = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.bot_uptime_lbl.setFont(font)
        self.bot_uptime_lbl.setObjectName("bot_uptime_lbl")
        self.horizontalLayout_3.addWidget(self.bot_uptime_lbl)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.bot_uptim_val = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.bot_uptim_val.setFont(font)
        self.bot_uptim_val.setObjectName("bot_uptim_val")
        self.horizontalLayout_3.addWidget(self.bot_uptim_val)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.module_lbl = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.module_lbl.setFont(font)
        self.module_lbl.setObjectName("module_lbl")
        self.horizontalLayout_5.addWidget(self.module_lbl)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.module_val = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.module_val.setFont(font)
        self.module_val.setObjectName("module_val")
        self.horizontalLayout_5.addWidget(self.module_val)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.conn_sts_lbl = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.conn_sts_lbl.setFont(font)
        self.conn_sts_lbl.setObjectName("conn_sts_lbl")
        self.horizontalLayout_4.addWidget(self.conn_sts_lbl)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.conn_sts_val = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.conn_sts_val.setFont(font)
        self.conn_sts_val.setObjectName("conn_sts_val")
        self.horizontalLayout_4.addWidget(self.conn_sts_val)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.widget2 = QtWidgets.QWidget(Form)
        self.widget2.setGeometry(QtCore.QRect(270, 110, 181, 111))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.conn_sts_lbl_2 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.conn_sts_lbl_2.setFont(font)
        self.conn_sts_lbl_2.setAlignment(QtCore.Qt.AlignCenter)
        self.conn_sts_lbl_2.setObjectName("conn_sts_lbl_2")
        self.verticalLayout_3.addWidget(self.conn_sts_lbl_2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.progressBar = QtWidgets.QProgressBar(self.widget2)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_3.addWidget(self.progressBar)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem7)
        self.progressBar_2 = QtWidgets.QProgressBar(self.widget2)
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setObjectName("progressBar_2")
        self.verticalLayout_3.addWidget(self.progressBar_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.shutdown_btn_2.setText(_translate("Form", "Reboot"))
        self.shutdown_btn.setText(_translate("Form", "Shutdown"))
        self.label.setText(_translate("Form", "Multi-Purpose Covid-19 Robot"))
        self.timeEdit.setDisplayFormat(_translate("Form", "hh:mm:A"))
        self.dateEdit.setDisplayFormat(_translate("Form", "yyyy/MM/dd"))
        self.batt_lbl.setText(_translate("Form", "Battery"))
        self.cpu_temp_lbl.setText(_translate("Form", "CPU Temp : "))
        self.cpu_temp_val.setText(_translate("Form", "62\'C"))
        self.bot_uptime_lbl.setText(_translate("Form", "Bot Uptime : "))
        self.bot_uptim_val.setText(_translate("Form", "txt"))
        self.module_lbl.setText(_translate("Form", "Module Att. : "))
        self.module_val.setText(_translate("Form", "txt"))
        self.conn_sts_lbl.setText(_translate("Form", "Conn. status : "))
        self.conn_sts_val.setText(_translate("Form", "txt"))
        self.conn_sts_lbl_2.setText(_translate("Form", "Obstacle"))
