# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_win_base.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(480, 320)
        self.title_lbl = QtWidgets.QLabel(Form)
        self.title_lbl.setGeometry(QtCore.QRect(20, 10, 446, 37))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.title_lbl.setFont(font)
        self.title_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.title_lbl.setObjectName("title_lbl")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 90, 222, 124))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cpu_temp_lbl = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.cpu_temp_lbl.setFont(font)
        self.cpu_temp_lbl.setObjectName("cpu_temp_lbl")
        self.horizontalLayout.addWidget(self.cpu_temp_lbl)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cpu_temp_val = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.cpu_temp_val.setFont(font)
        self.cpu_temp_val.setObjectName("cpu_temp_val")
        self.horizontalLayout.addWidget(self.cpu_temp_val)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.bot_uptime_lbl = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.bot_uptime_lbl.setFont(font)
        self.bot_uptime_lbl.setObjectName("bot_uptime_lbl")
        self.horizontalLayout_3.addWidget(self.bot_uptime_lbl)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.bot_uptim_val = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.bot_uptim_val.setFont(font)
        self.bot_uptim_val.setObjectName("bot_uptim_val")
        self.horizontalLayout_3.addWidget(self.bot_uptim_val)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.module_lbl = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.module_lbl.setFont(font)
        self.module_lbl.setObjectName("module_lbl")
        self.horizontalLayout_5.addWidget(self.module_lbl)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.module_val = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.module_val.setFont(font)
        self.module_val.setObjectName("module_val")
        self.horizontalLayout_5.addWidget(self.module_val)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.conn_sts_lbl = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.conn_sts_lbl.setFont(font)
        self.conn_sts_lbl.setObjectName("conn_sts_lbl")
        self.horizontalLayout_4.addWidget(self.conn_sts_lbl)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.conn_sts_val = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.conn_sts_val.setFont(font)
        self.conn_sts_val.setObjectName("conn_sts_val")
        self.horizontalLayout_4.addWidget(self.conn_sts_val)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.shutdown_btn = QtWidgets.QPushButton(Form)
        self.shutdown_btn.setGeometry(QtCore.QRect(20, 250, 181, 23))
        self.shutdown_btn.setObjectName("shutdown_btn")
        self.reboot_btn = QtWidgets.QPushButton(Form)
        self.reboot_btn.setGeometry(QtCore.QRect(270, 250, 181, 23))
        self.reboot_btn.setObjectName("reboot_btn")
        self.dateEdit = QtWidgets.QDateEdit(Form)
        self.dateEdit.setGeometry(QtCore.QRect(330, 160, 121, 32))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.dateEdit.setFont(font)
        self.dateEdit.setReadOnly(True)
        self.dateEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dateEdit.setObjectName("dateEdit")
        self.timeEdit = QtWidgets.QTimeEdit(Form)
        self.timeEdit.setGeometry(QtCore.QRect(340, 200, 111, 32))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.timeEdit.setFont(font)
        self.timeEdit.setFrame(True)
        self.timeEdit.setReadOnly(True)
        self.timeEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.timeEdit.setObjectName("timeEdit")
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(310, 80, 143, 58))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget1)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.bat1_lbl = QtWidgets.QLabel(self.layoutWidget1)
        self.bat1_lbl.setObjectName("bat1_lbl")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.bat1_lbl)
        self.bat1_pb = QtWidgets.QProgressBar(self.layoutWidget1)
        self.bat1_pb.setProperty("value", 24)
        self.bat1_pb.setObjectName("bat1_pb")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.bat1_pb)
        self.bat2_lbl = QtWidgets.QLabel(self.layoutWidget1)
        self.bat2_lbl.setObjectName("bat2_lbl")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.bat2_lbl)
        self.bat2_pb = QtWidgets.QProgressBar(self.layoutWidget1)
        self.bat2_pb.setProperty("value", 24)
        self.bat2_pb.setObjectName("bat2_pb")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.bat2_pb)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.title_lbl.setText(_translate("Form", "Multi-Purpose Covid-19 Robot"))
        self.cpu_temp_lbl.setText(_translate("Form", "CPU Temp : "))
        self.cpu_temp_val.setText(_translate("Form", "62\'C"))
        self.bot_uptime_lbl.setText(_translate("Form", "Bot Uptime : "))
        self.bot_uptim_val.setText(_translate("Form", "txt"))
        self.module_lbl.setText(_translate("Form", "Module Att. : "))
        self.module_val.setText(_translate("Form", "txt"))
        self.conn_sts_lbl.setText(_translate("Form", "Conn. status : "))
        self.conn_sts_val.setText(_translate("Form", "txt"))
        self.shutdown_btn.setText(_translate("Form", "Shutdown"))
        self.reboot_btn.setText(_translate("Form", "Reboot"))
        self.dateEdit.setDisplayFormat(_translate("Form", "yyyy/MM/dd"))
        self.timeEdit.setDisplayFormat(_translate("Form", "hh:mm:A"))
        self.bat1_lbl.setText(_translate("Form", "BAT-1"))
        self.bat2_lbl.setText(_translate("Form", "BAT-2"))
